"""Historical geometry reconstruction from geometry-coupled relational observables.

This module implements the "reverse Theseus" experiment described in the
attached specification: it asks whether later-state quantum-information and
causal observables, generated by a *geometry-coupled* relational process
(``historical_process.py``), carry enough information to reconstruct a hidden
historical geometry -- up to observational equivalence, not exact microscopic
recovery.

The existing independent-observable experiment in ``geometry_reconstruction.py``
remains a valid null baseline (EXP-HIST-NULL-001): it shows that observables
generated *independently* of geometry do not reconstruct it. This module adds
the geometry-coupled positive-control construction (EXP-HIST-COUPLED-001), an
information-retention sweep (EXP-HIST-RETENTION-001), an identifiability probe
(EXP-HIST-IDENT-001), and a randomized control on the coupled observables
(EXP-HIST-RANDOM-001).

No metric component, coordinate, or world/time label is ever exposed to the
reconstruction fit; ground truth is used only for evaluation after fitting.
Q and Delta_munu remain exactly zero throughout (see ``speculative_gate``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
import numpy as np
from scipy.optimize import least_squares

from .geometry import LorentzianEmbedding
from .geometry_reconstruction import (
    GeometryReconstructionReport,
    MultiSeedReconstructionReport,
    run_baseline_geometry_reconstruction,
    run_multi_seed_reconstruction,
)
from .gr import conformal_geometry, minkowski_geometry
from .ground_truth import GroundTruthWorld
from .historical_process import HistoricalProcessResult, build_geometry_coupled_history, historical_intervention_response
from .information import InformationCausalityEngine
from .speculative_gate import BaselineGate

MODELING_ASSUMPTION = "MODELING_ASSUMPTION"

NULL = "NULL"
RESTRICTED = "RESTRICTED"
FLEXIBLE = "FLEXIBLE"

IDENTIFIABLE = "IDENTIFIABLE"
NON_IDENTIFIABLE = "INFORMATIONALLY_NON_IDENTIFIABLE"

HISTORICAL_RECONSTRUCTION_SUPPORTED = "HISTORICAL_RECONSTRUCTION_SUPPORTED"
HISTORICAL_RECONSTRUCTION_UNSTABLE = "HISTORICAL_RECONSTRUCTION_UNSTABLE"
INFORMATION_INSUFFICIENT = "INFORMATION_INSUFFICIENT"
REPRESENTATION_INSUFFICIENT = "REPRESENTATION_INSUFFICIENT"
OPTIMIZATION_INSUFFICIENT = "OPTIMIZATION_INSUFFICIENT"
OBSERVABLES_NON_IDENTIFYING = "OBSERVABLES_NON_IDENTIFYING"


# ---------------------------------------------------------------------------
# Observable construction
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class HistoricalObservables:
    """Later-state observable bundle O_t1; never contains coordinates or metric data."""

    pairwise_information: np.ndarray
    multipartite_information: dict[tuple[int, int, int], float]
    intervention_tensor: np.ndarray
    causal_estimate: np.ndarray
    event_count: int
    labels: tuple[str, ...] = (
        "pairwise_mutual_information",
        "multipartite_information",
        "intervention_response_tensor",
        "causal_estimate",
    )

    def flatten(self) -> np.ndarray:
        upper = np.triu_indices(self.event_count, k=1)
        parts = [self.pairwise_information[upper]]
        if self.multipartite_information:
            parts.append(np.array(list(self.multipartite_information.values()), dtype=float))
        parts.append(self.intervention_tensor.ravel())
        return np.concatenate(parts)


def _estimate_causal_matrix(tensor: np.ndarray, threshold: float = 0.02) -> np.ndarray:
    """Derive a causal-direction estimate from observed responses only (no ground truth)."""
    count = tensor.shape[0]
    matrix = np.zeros((count, count), dtype=bool)
    for source in range(count):
        for target in range(count):
            if source == target:
                continue
            matrix[source, target] = tensor[source, target] > threshold and tensor[source, target] >= tensor[target, source]
    return matrix


def build_historical_observables(process: HistoricalProcessResult, world: GroundTruthWorld) -> HistoricalObservables:
    engine = InformationCausalityEngine(process.system)
    pairwise = engine.mutual_information_matrix()
    multipartite = engine.multipartite_information_triples() if process.event_count >= 3 else {}
    causal_response = historical_intervention_response(world, process.retention, process.length_scale)
    causal_estimate = _estimate_causal_matrix(causal_response.tensor)
    tensor_3d = causal_response.tensor[:, :, np.newaxis]
    return HistoricalObservables(pairwise, multipartite, tensor_3d, causal_estimate, process.event_count)


def randomize_historical_observables(observables: HistoricalObservables, seed: int) -> HistoricalObservables:
    """Randomized/null control: permute observables to preserve marginals but destroy pairing."""
    rng = np.random.default_rng(seed)
    count = observables.event_count
    upper = np.triu_indices(count, k=1)
    values = observables.pairwise_information[upper].copy()
    rng.shuffle(values)
    randomized_information = np.zeros_like(observables.pairwise_information)
    randomized_information[upper] = values
    randomized_information[(upper[1], upper[0])] = values

    randomized_multipartite = dict(observables.multipartite_information)
    if randomized_multipartite:
        keys = list(randomized_multipartite.keys())
        shuffled_values = np.array(list(randomized_multipartite.values()), dtype=float)
        rng.shuffle(shuffled_values)
        randomized_multipartite = dict(zip(keys, shuffled_values))

    order = rng.permutation(count)
    randomized_tensor = observables.intervention_tensor[order][:, order]
    randomized_causal = observables.causal_estimate[order][:, order]
    return HistoricalObservables(randomized_information, randomized_multipartite, randomized_tensor, randomized_causal, count)


# ---------------------------------------------------------------------------
# Reconstruction baselines: NULL / RESTRICTED / FLEXIBLE
# ---------------------------------------------------------------------------


def _pair_split(event_count: int, seed: int) -> tuple[list[tuple[int, int]], list[tuple[int, int]], list[tuple[int, int]]]:
    pairs = [(first, second) for first in range(event_count) for second in range(first + 1, event_count)]
    rng = np.random.default_rng(seed)
    rng.shuffle(pairs)
    train_end = max(1, int(0.6 * len(pairs)))
    validation_end = max(train_end + 1, int(0.8 * len(pairs)))
    return pairs[:train_end], pairs[train_end:validation_end], pairs[validation_end:]


def _dissimilarity_from_information(information: np.ndarray) -> np.ndarray:
    max_information = max(float(np.max(information)), 1e-12)
    return -np.log((information + 1e-12) / (max_information + 1e-12))


@dataclass(frozen=True)
class BaselineReport:
    model_id: str
    parameter_count: int
    train_loss: float
    validation_loss: float
    test_loss: float
    causal_precision: float
    causal_recall: float
    causal_f1: float
    coordinate_relative_error: float
    curvature_invariant_error: float
    fitted_scale: float | None
    mapping_is_physical_law: bool = False


def _residuals(
    flat: np.ndarray,
    event_count: int,
    flexible: bool,
    selected_pairs: list[tuple[int, int]],
    dissimilarity: np.ndarray,
    causal_estimate: np.ndarray,
) -> np.ndarray:
    coordinates = flat[: event_count * 4].reshape(event_count, 4)
    scale = flat[event_count * 4] if flexible else 0.0
    values = []
    for first, second in selected_pairs:
        difference = coordinates[first] - coordinates[second]
        midpoint_time = 0.5 * (coordinates[first, 0] + coordinates[second, 0])
        conformal_factor = np.exp(2 * scale * midpoint_time) if flexible else 1.0
        eta = np.diag([-1.0, 1.0, 1.0, 1.0])
        separation = conformal_factor * float(difference @ eta @ difference)
        values.append(np.sqrt(abs(separation) + 1e-12) - dissimilarity[first, second])
    for source, target in zip(*np.where(causal_estimate)):
        difference = coordinates[source] - coordinates[target]
        eta = np.diag([-1.0, 1.0, 1.0, 1.0])
        separation = float(difference @ eta @ difference)
        values.append(max(0.0, separation))
        values.append(max(0.0, coordinates[source, 0] - coordinates[target, 0]))
    values.extend(coordinates[0].tolist())
    if flexible:
        values.append(0.1 * scale)
    return np.asarray(values, dtype=float)


def _fit(
    observables: HistoricalObservables,
    mode: str,
    seed: int,
    true_coordinates: np.ndarray,
    true_scalar_curvature: float,
    reference_point: np.ndarray,
) -> BaselineReport:
    event_count = observables.event_count
    train_pairs, validation_pairs, test_pairs = _pair_split(event_count, seed)
    dissimilarity = _dissimilarity_from_information(observables.pairwise_information)
    rng = np.random.default_rng(seed)

    if mode == NULL:
        fitted = np.zeros((event_count, 4))
        scale_hat: float | None = None
        parameter_count = 0
    else:
        flexible = mode == FLEXIBLE
        initial = rng.normal(scale=0.2, size=(event_count, 4))
        initial[:, 0] = np.arange(event_count, dtype=float) + rng.normal(scale=0.05, size=event_count)
        initial[0] = 0.0
        initial_flat = initial.ravel()
        if flexible:
            initial_flat = np.concatenate([initial_flat, [0.0]])
        result = least_squares(
            lambda values: _residuals(values, event_count, flexible, train_pairs, dissimilarity, observables.causal_estimate),
            initial_flat,
            max_nfev=800,
        ).x
        fitted = result[: event_count * 4].reshape(event_count, 4)
        scale_hat = float(result[event_count * 4]) if flexible else 0.0
        parameter_count = event_count * 4 + (1 if flexible else 0)

    def pair_loss(selected_pairs: list[tuple[int, int]]) -> float:
        if not selected_pairs:
            return 0.0
        flat = fitted.ravel() if scale_hat is None else np.concatenate([fitted.ravel(), [scale_hat]])
        values = _residuals(flat, event_count, scale_hat is not None, selected_pairs, dissimilarity, observables.causal_estimate)
        return float(np.mean(values[: len(selected_pairs)] ** 2))

    embedding = LorentzianEmbedding(fitted)
    causal_metrics = embedding.compare_causal_relations(observables.causal_estimate)
    scale_norm = max(float(np.linalg.norm(true_coordinates)), 1e-12)
    coordinate_error = float(np.linalg.norm(fitted - true_coordinates) / scale_norm)

    effective_scale = scale_hat if scale_hat is not None else 0.0
    fitted_geometry = conformal_geometry(effective_scale) if abs(effective_scale) > 1e-12 else minkowski_geometry()
    fitted_curvature = float(fitted_geometry.curvature_tensors(reference_point).scalar_curvature)
    curvature_error = abs(fitted_curvature - true_scalar_curvature)

    return BaselineReport(
        mode,
        parameter_count,
        pair_loss(train_pairs),
        pair_loss(validation_pairs),
        pair_loss(test_pairs),
        float(causal_metrics["precision"]),
        float(causal_metrics["recall"]),
        float(causal_metrics["f1"]),
        coordinate_error,
        curvature_error,
        scale_hat,
    )


def compare_historical_baselines(
    world: GroundTruthWorld,
    observables: HistoricalObservables,
    seed: int,
    true_scale: float = 0.0,
) -> dict[str, BaselineReport]:
    """Fit NULL / RESTRICTED / FLEXIBLE reconstructions on the SAME observable bundle and split."""
    reference_point = world.coordinates.mean(axis=0)
    true_scalar_curvature = float(world.geometry.curvature_tensors(reference_point).scalar_curvature)
    return {
        mode: _fit(observables, mode, seed, world.coordinates, true_scalar_curvature, reference_point)
        for mode in (NULL, RESTRICTED, FLEXIBLE)
    }


# ---------------------------------------------------------------------------
# Identifiability (EXP-HIST-IDENT-001)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IdentifiabilityReport:
    world_a: str
    world_b: str
    observable_distance: float
    classification: str
    tolerance: float


def run_identifiability_test(world_a: GroundTruthWorld, world_b: GroundTruthWorld, retention: float = 1.0, tolerance: float = 1e-6) -> IdentifiabilityReport:
    BaselineGate().validate()
    observables_a = build_historical_observables(build_geometry_coupled_history(world_a, retention), world_a)
    observables_b = build_historical_observables(build_geometry_coupled_history(world_b, retention), world_b)
    distance = float(np.linalg.norm(observables_a.flatten() - observables_b.flatten()))
    classification = NON_IDENTIFIABLE if distance <= tolerance else IDENTIFIABLE
    return IdentifiabilityReport(world_a.world_id, world_b.world_id, distance, classification, tolerance)


# ---------------------------------------------------------------------------
# Information retention (EXP-HIST-RETENTION-001)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RetentionPoint:
    eta: float
    f_geom: float
    test_loss: float
    causal_f1: float
    coordinate_relative_error: float


@dataclass(frozen=True)
class RetentionCurveReport:
    world_id: str
    points: tuple[RetentionPoint, ...]

    @property
    def etas(self) -> tuple[float, ...]:
        return tuple(point.eta for point in self.points)

    @property
    def scores(self) -> tuple[float, ...]:
        return tuple(point.f_geom for point in self.points)


def _f_geom(causal_f1: float, coordinate_relative_error: float) -> float:
    """Benchmark score, not a physical law: mixes causal agreement and coordinate diagnostic error."""
    return float(0.5 * causal_f1 + 0.5 * (1.0 - min(1.0, coordinate_relative_error)))


def run_information_retention_curve(world: GroundTruthWorld, etas: tuple[float, ...] = (0.0, 0.2, 0.4, 0.6, 0.8, 1.0), seed: int = 1234) -> RetentionCurveReport:
    BaselineGate().validate()
    points = []
    for eta in etas:
        process = build_geometry_coupled_history(world, retention=eta)
        observables = build_historical_observables(process, world)
        report = compare_historical_baselines(world, observables, seed)[FLEXIBLE]
        points.append(RetentionPoint(eta, _f_geom(report.causal_f1, report.coordinate_relative_error), report.test_loss, report.causal_f1, report.coordinate_relative_error))
    return RetentionCurveReport(world.world_id, tuple(points))


# ---------------------------------------------------------------------------
# Multi-seed statistics
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SeedStatistics:
    seed_count: int
    mean: float
    std: float
    median: float
    minimum: float
    maximum: float
    per_seed: tuple[float, ...]


def _seed_statistics(values: tuple[float, ...]) -> SeedStatistics:
    array = np.asarray(values, dtype=float)
    return SeedStatistics(len(values), float(np.mean(array)), float(np.std(array)), float(np.median(array)), float(np.min(array)), float(np.max(array)), values)


# ---------------------------------------------------------------------------
# Top-level experiment report and scientific classification
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class HistoricalExperimentReport:
    experiment_id: str
    geometry_hidden: bool
    observable_source: str
    coupling_mechanism: str
    baselines: dict[str, BaselineReport]
    seed_statistics: dict[str, SeedStatistics]
    q_norm: float = 0.0
    delta_norm: float = 0.0
    claims_new_physics: bool = False
    claims_time_travel: bool = False


def run_coupled_experiment(world: GroundTruthWorld, seeds: tuple[int, ...] = tuple(range(10)), retention: float = 1.0) -> HistoricalExperimentReport:
    """EXP-HIST-COUPLED-001: geometry-coupled relational process -> historical geometry."""
    BaselineGate().validate()
    process = build_geometry_coupled_history(world, retention=retention)
    observables = build_historical_observables(process, world)
    per_seed = [compare_historical_baselines(world, observables, seed) for seed in seeds]
    seed_statistics = {
        mode: _seed_statistics(tuple(reports[mode].test_loss for reports in per_seed))
        for mode in (NULL, RESTRICTED, FLEXIBLE)
    }
    return HistoricalExperimentReport(
        "EXP-HIST-COUPLED-001",
        True,
        f"geometry_coupled_process[{world.world_id}]",
        process.coupling_mechanism,
        per_seed[0],
        seed_statistics,
    )


def run_randomized_control_experiment(world: GroundTruthWorld, seeds: tuple[int, ...] = tuple(range(10)), retention: float = 1.0) -> HistoricalExperimentReport:
    """EXP-HIST-RANDOM-001: pairwise-permutation control applied to the coupled observables."""
    BaselineGate().validate()
    process = build_geometry_coupled_history(world, retention=retention)
    observables = build_historical_observables(process, world)
    per_seed = [compare_historical_baselines(world, randomize_historical_observables(observables, seed), seed) for seed in seeds]
    seed_statistics = {
        mode: _seed_statistics(tuple(reports[mode].test_loss for reports in per_seed))
        for mode in (NULL, RESTRICTED, FLEXIBLE)
    }
    return HistoricalExperimentReport(
        "EXP-HIST-RANDOM-001",
        True,
        f"randomized_pairwise_permutation[{world.world_id}]",
        "none_pairwise_permutation_control",
        per_seed[0],
        seed_statistics,
    )


@dataclass(frozen=True)
class NullBaselineExperimentReport:
    experiment_id: str
    report: GeometryReconstructionReport
    multi_seed: MultiSeedReconstructionReport


def run_null_baseline_experiment(seed: int = 1234, seeds: tuple[int, ...] = tuple(range(10))) -> NullBaselineExperimentReport:
    """EXP-HIST-NULL-001: the existing independent-observable experiment, preserved unchanged.

    Scientific meaning: geometry-independent observables -> attempted geometry
    reconstruction. The previous negative result remains valid; it is not
    reinterpreted as proof that historical reconstruction in general is impossible.
    """
    report = run_baseline_geometry_reconstruction(seed)
    multi_seed = run_multi_seed_reconstruction(seeds)
    return NullBaselineExperimentReport("EXP-HIST-NULL-001", report, multi_seed)


def classify_historical_reconstruction(
    coupled: HistoricalExperimentReport,
    randomized: HistoricalExperimentReport,
    identifiability: list[IdentifiabilityReport],
    retention_curve: RetentionCurveReport,
    test_loss_threshold: float = 0.25,
    causal_f1_threshold: float = 0.8,
) -> str:
    """Return the weakest scientifically defensible classification, per spec section 20."""
    if any(report.classification == NON_IDENTIFIABLE for report in identifiability):
        return OBSERVABLES_NON_IDENTIFYING

    flexible = coupled.seed_statistics[FLEXIBLE]
    restricted = coupled.seed_statistics[RESTRICTED]
    randomized_flexible = randomized.seed_statistics[FLEXIBLE]

    coupled_report = coupled.baselines[FLEXIBLE]
    optimizer_failed = flexible.mean > 1.0 and restricted.mean > 1.0

    if optimizer_failed:
        return OPTIMIZATION_INSUFFICIENT

    beats_randomized = flexible.mean < randomized_flexible.mean
    beats_restricted = flexible.mean <= restricted.mean
    monotonic_ish = retention_curve.scores[-1] >= retention_curve.scores[0]

    if not beats_randomized:
        return INFORMATION_INSUFFICIENT

    if not beats_restricted or coupled_report.curvature_invariant_error > 1.0:
        return REPRESENTATION_INSUFFICIENT

    success = (
        flexible.mean < test_loss_threshold
        and coupled_report.causal_f1 >= causal_f1_threshold
        and beats_randomized
        and beats_restricted
        and monotonic_ish
    )
    if success and flexible.std < test_loss_threshold:
        return HISTORICAL_RECONSTRUCTION_SUPPORTED
    if success:
        return HISTORICAL_RECONSTRUCTION_UNSTABLE
    return HISTORICAL_RECONSTRUCTION_UNSTABLE
